specVersion: 1.0.0
name: 'repo'
version: 1.0.0
runner:
  node:
    name: '@subql/node'
    version: ^1.0.0
  query:
    name: '@subql/query'
    version: ^1.0.0
description: >-
  NFTMart: A professional NFT market
repository: 'https://github.com/NFTT-studio/nftmart-subql'
schema:
  file: ./schema.graphql
network:
  chainId: '0xfcf9074303d8f319ad1bf0195b145871977e7c375883b834247cb01ff22f51f9'
  endpoint: 'wss://mainnet.nftmart.io/rpc/ws'
# dictionary: 'https://api.subquery.network/sq/subquery/dictionary-polkadot'
# genesisHash: '0xfcf9074303d8f319ad1bf0195b145871977e7c375883b834247cb01ff22f51f9'
  chaintypes:
    file: ./chaintypes.yaml
dataSources:
  - kind: substrate/Runtime
    startBlock: 443322
    mapping:
      file: ./dist/index.js
      handlers:
        - handler: handleBlock
          kind: substrate/BlockHandler
        - handler: handleEvent
          kind: substrate/EventHandler
        - handler: handleCall
          kind: substrate/CallHandler
