specVersion: 0.0.1
description: nftmart graphql server
repository: https://github.com/NFTT-studio/nftmart-query
schema: ./schema.graphql
network:
  endpoint: wss://polkadot.api.onfinality.io/public-ws
  types:
    Properties: u8
    NFTMetadata: Vec<u8>
    BlockNumber: u32
    BlockNumberOf: BlockNumber
    OrderData:
      currencyId: Compact<CurrencyIdOf>
      price: Compact<Balance>
      deposit: Compact<Balance>
      deadline: Compact<BlockNumberOf>
      categoryId: Compact<CategoryIdOf>
    CategoryId: u32
    CategoryIdOf: CategoryId
    CategoryData:
      metadata: NFTMetadata
      nftCount: Compact<Balance>
    CurrencyId: u32
    CurrencyIdOf: CurrencyId
    Amount: i128
    AmountOf: Amount
    ClassId: u32
    ClassIdOf: ClassId
    ClassInfoOf:
      metadata: NFTMetadata
      totalIssuance: TokenId
      owner: AccountId
      data: ClassData
    ClassData:
      deposit: Compact<Balance>
      properties: Properties
      name: Vec<u8>
      description: Vec<u8>
      createBlock: Compact<BlockNumberOf>
    TokenId: u64
    TokenIdOf: TokenId
    TokenInfoOf:
      metadata: NFTMetadata
      owner: AccountId
      data: TokenData
    TokenData:
      deposit: Compact<Balance>
      createBlock: Compact<BlockNumberOf>

dataSources:
  - name: main
    kind: substrate/Runtime
    startBlock: 1
    mapping:
      handlers:
        - handler: handleBlock
          kind: substrate/BlockHandler
        - handler: handleEvent
          kind: substrate/EventHandler
          filter:
            module: balances
            method: Deposit
        - handler: handleCall
          kind: substrate/CallHandler
