specVersion: 0.0.2
description: ""
repository: "https://github.com/subqns/nftmart-subql.git"
schema: ./schema.graphql
network:
# endpoint: wss://mandala6.laminar.codes
# endpoint: "ws://8.136.111.191:9944"
# endpoint: ws://81.70.132.13:9944
  endpoint: ws://tmp-chain.bcdata.top
  types:
    Properties: u8
    NFTMetadata: Vec<u8>
    BlockNumber: u32
    BlockNumberOf: BlockNumber
    OrderData:
      currencyId: Compact<CurrencyIdOf>
      price: Compact<Balance>
      deposit: Compact<Balance>
      deadline: Compact<BlockNumberOf>
      categoryId: Compact<CategoryIdOf>
    CategoryId: u32
    CategoryIdOf: CategoryId
    CategoryData:
      metadata: NFTMetadata
      nftCount: Compact<Balance>
    CurrencyId: u32
    CurrencyIdOf: CurrencyId
    Amount: i128
    AmountOf: Amount
    ClassId: u32
    ClassIdOf: ClassId
    ClassInfoOf:
      metadata: NFTMetadata
      totalIssuance: TokenId
      owner: AccountId
      data: ClassData
    ClassData:
      deposit: Compact<Balance>
      properties: Properties
      name: Vec<u8>
      description: Vec<u8>
      createBlock: Compact<BlockNumberOf>
    TokenId: u64
    TokenIdOf: TokenId
    TokenInfoOf:
      metadata: NFTMetadata
      owner: AccountId
      data: TokenData
    TokenData:
      deposit: Compact<Balance>
      createBlock: Compact<BlockNumberOf>
dataSources:
  - name: main
    kind: substrate/Runtime
    startBlock: 0 # nothing interesting to see before this
    mapping:
      handlers:
        - handler: handleBlock
          kind: substrate/BlockHandler
        - handler: handleEvent
          kind: substrate/EventHandler
        - handler: handleCall
          kind: substrate/CallHandler
